# Generated by Django 5.0.6 on 2024-06-02 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJuego', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('consola', models.CharField(choices=[('PS2', 'PLAYSTATION 2'), ('PS4', 'PLAYSTATION 4'), ('PS5', 'PLAYSTATION 5'), ('PS1', 'PLAYSTATION 1'), ('PS3', 'PLAYSTATION 3')], max_length=3)),
                ('precio', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('copias', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('descripcion', models.TextField()),
                ('foto_juego', models.ImageField(upload_to='juegos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nomb_usuario', models.CharField(max_length=13)),
                ('sexo', models.CharField(choices=[('O', 'OTRO'), ('M', 'MASCULINO'), ('F', 'FEMENINO')], max_length=1)),
                ('correo', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefono', models.CharField(max_length=8)),
                ('ciudad', models.CharField(choices=[('CONCEPCIÓN', 'CONCEPCIÓN'), ('VALPARÍSO', 'VALPARAÍSO'), ('SANTIAGO', 'SANTIAGO')], max_length=20)),
                ('direccion', models.CharField(max_length=75)),
            ],
        ),
    ]
