# Generated by Django 5.0.6 on 2024-06-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='nombreJuego',
            new_name='nomb_juego',
        ),
        migrations.RenameField(
            model_name='juego',
            old_name='copias',
            new_name='stock',
        ),
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(choices=[('PS4', 'PLAYSTATION 4'), ('PS5', 'PLAYSTATION 5'), ('PS2', 'PLAYSTATION 2'), ('PS1', 'PLAYSTATION 1'), ('PS3', 'PLAYSTATION 3')], max_length=3),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(choices=[('VALPARÍSO', 'VALPARAÍSO'), ('SANTIAGO', 'SANTIAGO'), ('CONCEPCIÓN', 'CONCEPCIÓN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('F', 'FEMENINO'), ('O', 'OTRO'), ('M', 'MASCULINO')], max_length=1),
        ),
    ]
