# Generated by Django 5.0.6 on 2024-06-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebstore', '0002_rename_nombrejuego_juego_nomb_juego_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(choices=[('PS3', 'PLAYSTATION 3'), ('PS4', 'PLAYSTATION 4'), ('PS5', 'PLAYSTATION 5'), ('PS2', 'PLAYSTATION 2'), ('PS1', 'PLAYSTATION 1')], max_length=3),
        ),
        migrations.AlterField(
            model_name='juego',
            name='foto_juego',
            field=models.ImageField(upload_to='juegos', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='nomb_juego',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nomb_usuario',
            field=models.CharField(max_length=13, verbose_name='Nombre de usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'MASCULINO'), ('O', 'OTRO'), ('F', 'FEMENINO')], max_length=1),
        ),
    ]
