# Generated by Django 5.0.6 on 2024-06-03 23:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebstore', '0003_alter_juego_consola_alter_juego_foto_juego_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gamewebstore.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(choices=[('PS4', 'PLAYSTATION 4'), ('PS1', 'PLAYSTATION 1'), ('PS2', 'PLAYSTATION 2'), ('PS3', 'PLAYSTATION 3'), ('PS5', 'PLAYSTATION 5')], max_length=3),
        ),
        migrations.AlterField(
            model_name='juego',
            name='precio',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='juego',
            name='stock',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(choices=[('SANTIAGO', 'SANTIAGO'), ('VALPARÍSO', 'VALPARAÍSO'), ('CONCEPCIÓN', 'CONCEPCIÓN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('O', 'OTRO'), ('M', 'MASCULINO'), ('F', 'FEMENINO')], max_length=1),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamewebstore.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamewebstore.juego')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamewebstore.pedido')),
            ],
        ),
    ]
