# Generated by Django 5.0.6 on 2024-06-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebstore', '0004_juego_vendedor_usuario_contraseña_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='producto',
            new_name='juego',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_creación',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(choices=[('PS4', 'PLAYSTATION 4'), ('PS1', 'PLAYSTATION 1'), ('PS5', 'PLAYSTATION 5'), ('PS3', 'PLAYSTATION 3'), ('PS2', 'PLAYSTATION 2')], max_length=3),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(choices=[('CONCEPCIÓN', 'CONCEPCIÓN'), ('VALPARÍSO', 'VALPARAÍSO'), ('SANTIAGO', 'SANTIAGO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO'), ('O', 'OTRO')], max_length=1),
        ),
    ]
