# Generated by Django 5.0.6 on 2024-06-03 23:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebstore', '0005_rename_producto_detallepedido_juego_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_creación',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(choices=[('PS1', 'PLAYSTATION 1'), ('PS5', 'PLAYSTATION 5'), ('PS3', 'PLAYSTATION 3'), ('PS2', 'PLAYSTATION 2'), ('PS4', 'PLAYSTATION 4')], max_length=3),
        ),
    ]
