# Generated by Django 5.0.6 on 2024-06-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebstore', '0007_remove_usuario_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_pedido',
        ),
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(choices=[('PS4', 'PLAYSTATION 4'), ('PS5', 'PLAYSTATION 5'), ('PS1', 'PLAYSTATION 1'), ('PS2', 'PLAYSTATION 2'), ('PS3', 'PLAYSTATION 3')], max_length=3),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('O', 'OTRO'), ('F', 'FEMENINO'), ('M', 'MASCULINO')], max_length=1),
        ),
    ]
