# Generated by Django 5.0.6 on 2024-06-06 00:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebstore', '0008_remove_pedido_fecha_pedido_alter_juego_consola_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(choices=[('PS5', 'PLAYSTATION 5'), ('PS2', 'PLAYSTATION 2'), ('PS3', 'PLAYSTATION 3'), ('PS1', 'PLAYSTATION 1'), ('PS4', 'PLAYSTATION 4')], max_length=3),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='EliminarUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('feliminar_u', models.ImageField(upload_to='del_user', verbose_name='Imagen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamewebstore.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SuspenderUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_dias', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fsuspender_u', models.ImageField(upload_to='susp_user', verbose_name='Imagen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamewebstore.usuario')),
            ],
        ),
    ]
