TIPO_SEXO={
    ("F","FEMENINO"),
    ("M","MASCULINO"),
    ("O","OTRO")
}

NOMB_CIUDAD={
    ("SANTIAGO", "SANTIAGO"),
    ("VALPARÍSO", "VALPARAÍSO"),
    ("CONCEPCIÓN", "CONCEPCIÓN")
}

TIPO_CONSOLA={
    ("PS1", "PLAYSTATION 1"),
    ("PS2", "PLAYSTATION 2"),
    ("PS3", "PLAYSTATION 3"),
    ("PS4", "PLAYSTATION 4"),
    ("PS5", "PLAYSTATION 5")
}